name: PHP Extension Updater
description: Monitors a given list of PHP extensions and opens a PR if newer versions exist.
author: pantheon-systems
branding:
  icon: file-plus
  color: yellow
inputs:
  dependencies-yml:
    description: The path to the list of dependencies in a dependencies.yml file.
    required: true
    type: string
    default: ''
  output-file:
    description: The path to a separate, plaintext file to update the changes to (in addition to dependencies.yml).
    required: false
    type: string
    default: ''
runs:
  using: composite
  steps:
    - name: Check Dependencies
      shell: bash
      uses: mikefarah/yq@master@v4
      run: ./bin/dependency-check-pr.sh