name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          dependencies-yml: ./fixtures/dependencies.yml
          output-file: ./fixtures/PHP_EXTENSION_VERSIONS
          dry-run: true
      - run: bash ./bin/test-textfile.sh ./fixtures/PHP_EXTENSION_VERSIONS
      - run: bash ./bin/validate-dependencies-yml-schema.sh ./fixtures/dependencies.yml
      - run: bash ./bin/test-dependencies-yml.sh ./fixtures/dependencies.yml
