name: Package Updater
on: 
  push:    
  schedule:
    - cron: '0 * * * *'
jobs:
  update:
    runs-on: ubuntu-latest
    name: Update Dependencies
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          dependencies-yml: ./fixtures/dependencies.yml